version: 1
record_prefix: "xyzrins:"
identity:
  title: Center for Open Neuroscience
  description: Open software frameworks, platforms, data, and methodologies for neuroscience and beyond.
  base_url: https://orinoco-lite.github.io/test-orinoco-downstream-website/
navigation:
  - name: About
    page_ref: /about/
    weight: 10
  - name: Projects
    page_ref: /projects/
    weight: 20
  - name: People
    page_ref: /persons/
    weight: 30
  - name: Publications
    page_ref: /publications/
    weight: 40
  - name: Outputs
    page_ref: /instruments/
    weight: 50
  - name: Explore
    page_ref: /explore/
    weight: 60
  - name: Engage
    page_ref: /engage/
    weight: 70
  - name: Support
    page_ref: /support/
    weight: 80
  - name: Contact
    page_ref: /contact/
    weight: 90
presentation:
  color_scheme: con
  default_appearance: light
  header_layout: hybrid
